before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    binary: forgeops
    goarch:
      - amd64
      - arm
      - arm64
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X github.com/ForgeRock/forgeops-cli/pkg/version.GitCommit={{.Env.GIT_COMMIT}}{{.Env.GIT_DIRTY}} 
      - -X github.com/ForgeRock/forgeops-cli/pkg/version.Version={{.Env.TAG_NAME}} 
      - -X github.com/ForgeRock/forgeops-cli/pkg/version.BuildDate={{.Env.BUILD_DATE}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: ForgeRock
    name: forgeops-cli
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
