timeout: 1200s
steps:
# Setup the workspace so we have a viable place to point GOPATH at.
- name: gcr.io/cloud-builders/go
  env: ['PROJECT_ROOT=github.com/ForgeRock/forgeops-cli']
  args: ['env']

- name: gcr.io/cloud-builders/go                                     
  env: ['PROJECT_ROOT=github.com/ForgeRock/forgeops-cli']            
  args: ['test', './...']                                            

# Create github release.
- name: goreleaser/goreleaser
  entrypoint: /bin/sh
  dir: gopath/src/github.com
  env: ['GOPATH=/workspace/gopath']
  args: ['-c', 'cd ForgeRock/forgeops-cli && make pr-build PR_NUMBER=$_PR_NUMBER' ]
  secretEnv: ['GITHUB_TOKEN']
secrets:
- kmsKeyName: projects/engineering-devops/locations/global/keyRings/engineering-devops/cryptoKeys/github-key
  secretEnv:
    GITHUB_TOKEN: |
      CiQAWHysaumBCi7eM+fysjiJWzP2vFq50c6h78JyNyyS3RJSQlASUQBqP6GPGGhZy6CwJOwzTvLf
      jhnEY3cT3uM0RunKcS1wXK+7q93BAmi3UsV7z2HWf3/ppWiwZTEepEd4X1S9NgVEQPTZuQ+ZJbdN
      q2BJRn6SVA==
artifacts:
  objects:
    location: 'gs://engineering-devops_cloudbuild/forgeops-cli-artifacts/$_PR_NUMBER'
    paths: ['dist/*']
