// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	watch "k8s.io/apimachinery/pkg/watch"
)

// ConditionFunction is an autogenerated mock type for the ConditionFunction type
type ConditionFunction struct {
	mock.Mock
}

// Execute provides a mock function with given fields: event, obj
func (_m *ConditionFunction) Execute(event watch.Event, obj *unstructured.Unstructured) (bool, error) {
	ret := _m.Called(event, obj)

	var r0 bool
	if rf, ok := ret.Get(0).(func(watch.Event, *unstructured.Unstructured) bool); ok {
		r0 = rf(event, obj)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(watch.Event, *unstructured.Unstructured) error); ok {
		r1 = rf(event, obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
